#!/usr/bin/python
#
# Copyright 2012 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import sys
import yaml
import json
import os

infile_path = sys.argv[1]
if infile_path == '-':
    infile = sys.stdin
else:
    infile = open(infile_path)

if len(sys.argv) > 2:
    indent = int(sys.argv[2])
else:
    indent = 2

intext = infile.read()
try:
    x = json.loads(intext)
except ValueError as e:
    if 'debug' in sys.argv:
        sys.stderr.write(str(e))
    x = yaml.load_all(intext)
    for doc in x:
        if indent:
            print(json.dumps(doc, indent=indent))
        else:
            print(json.dumps(doc))
else:
    if 'flow' in sys.argv:
        flow=True
    else:
        flow=False
    print yaml.safe_dump(x, default_flow_style=flow)
